import { createContext, useContext, useMemo, useState, useEffect } from 'react';

const STORAGE_KEY = 'nds-language';

const LANGUAGES = [
    { code: 'en', label: 'English', flag: '🇬🇧' },
    { code: 'it', label: 'Italiano', flag: '🇮🇹' },
    { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
];

const DICT = {
    en: {
        searchPlaceholder: 'Search products...',
        searchLabel: 'Search products',
        searchButton: 'Search',
        country: 'Country',
        currency: 'Currency',
        language: 'Language',
        returns: 'Returns',
        orders: '& Orders',
        deliverTo: 'Deliver to',
        welcome: 'Welcome to',
        heroLine: 'Big catalog energy, zero delivery anxiety.',
        freeDelivery: 'FREE delivery on every imaginary order',
        results: 'results',
        result: 'result',
        page: 'Page',
        of: 'of',
        previous: 'Previous',
        next: 'Next',
        sortBy: 'Sort by',
        perPage: 'Per page',
        relevance: 'Relevance',
        priceLowHigh: 'Price: Low to High',
        priceHighLow: 'Price: High to Low',
        ratingHighLow: 'Rating: High to Low',
        newest: 'Newest',
        retry: 'Retry',
        flashSale: 'Flash Sale',
        saleHeadline: '50% OFF everything',
        saleSubline: 'Every item at half price, even the houses.',
        saleEndsIn: 'Ends in',
        saveLabel: 'You save',
        off: 'OFF',
        lightningDeal: 'Lightning Deal',
        lightningDeals: 'Lightning Deals',
        lightningDealsHint: 'Refreshes hourly',
        needohsTitle: 'NeeDoh Squishy Shop',
        needohsSubtitle: 'Squish now, wait later. Every NeeDoh ships in 6-9 weeks.',
        needohsShipping: 'Ships in 6-9 weeks',
        couponTitle: 'Have a coupon?',
        couponPlaceholder: 'Enter code',
        couponApply: 'Apply',
        couponRemove: 'Remove',
        couponSurprise: '🎲 Surprise me',
        couponApplied: 'Coupon applied',
        couponInvalid: "That code doesn't exist. Try Surprise me!",
        couponDiscount: 'Coupon discount',
        playAndWin: 'Play &',
        winFree: 'Win Free Stuff',
        gamesTitle: 'Play & Win Free Prizes',
        gamesSubtitle: 'Spin, pull, and bet your way to free stuff that lands in your cart at $0.',
        gamesPrizePool: 'Prize pool',
        gameFree: 'FREE',
        gameWheelTitle: 'Spin the Wheel',
        gameWheelDesc: 'One spin, one prize. Where it stops, nobody knows.',
        gameSlotTitle: 'Slot Machine',
        gameSlotDesc: 'Match three symbols to win the matching prize.',
        gameRouletteTitle: 'Roulette',
        gameRouletteDesc: 'Pick a colour and spin. Green pays the jackpot!',
        gameSpin: 'Spin',
        gamePull: 'Pull the lever',
        gameSpinning: 'Spinning...',
        gameYouWon: 'You won',
        gameTryAgain: 'So close! Try again.',
        gameAddFree: 'Add to cart for free',
        gameAddedFree: 'Added free!',
        gameBetLabel: 'Choose your bet',
        gameBet_red: 'Red',
        gameBet_black: 'Black',
        gameBet_green: 'Green',
        aboutTitle: 'Why NeverDeliver exists',
        aboutLead: 'NeverDeliver is a playful shopping simulator, basically a game. Nothing here is real: no products ship, no cards are charged, and no money ever changes hands.',
        aboutCareIntro: 'It’s built as a safe place to enjoy the fun of shopping without any of the risk:',
        aboutCare1: 'Feel the dopamine of hunting deals, filling a cart, and “checking out” with zero financial consequences.',
        aboutCare2: 'A gentler outlet for anyone who struggles with compulsive shopping or shopping addiction.',
        aboutCare3: 'A safer sandbox for vulnerable people, including those living with dementia, who can be targeted by scams and fake online stores.',
        aboutCare4: 'A low-stakes way for people with ADHD to scratch the impulse-buy itch, chase a little novelty, and enjoy the thrill of a new purchase without the buyer’s remorse.',
        aboutFree: 'This project is completely free, with no ads and nothing to buy, and it always will be.',
        writeReview: 'Write a review',
        yourName: 'Your name',
        reviewTitle: 'Review title',
        reviewBody: 'Your review',
        yourRating: 'Your rating',
        submitReview: 'Submit review',
        cancel: 'Cancel',
        yourReviewBadge: 'Your review',
        reviewPosted: 'Review submitted! (Only you can see it.)',
        deleteReview: 'Delete my review',
    },
    it: {
        searchPlaceholder: 'Cerca prodotti...',
        searchLabel: 'Cerca prodotti',
        searchButton: 'Cerca',
        country: 'Paese',
        currency: 'Valuta',
        language: 'Lingua',
        returns: 'Resi',
        orders: 'e ordini',
        deliverTo: 'Consegna a',
        welcome: 'Benvenuto su',
        heroLine: 'Catalogo enorme, zero ansia da consegna.',
        freeDelivery: 'Consegna GRATIS su ogni ordine immaginario',
        results: 'risultati',
        result: 'risultato',
        page: 'Pagina',
        of: 'di',
        previous: 'Indietro',
        next: 'Avanti',
        sortBy: 'Ordina per',
        perPage: 'Per pagina',
        relevance: 'Pertinenza',
        priceLowHigh: 'Prezzo: crescente',
        priceHighLow: 'Prezzo: decrescente',
        ratingHighLow: 'Valutazione: alta-bassa',
        newest: 'Piu recenti',
        retry: 'Riprova',
        flashSale: 'Offerta Lampo',
        saleHeadline: '50% di SCONTO su tutto',
        saleSubline: 'Ogni articolo a meta prezzo, anche le case.',
        saleEndsIn: 'Finisce tra',
        saveLabel: 'Risparmi',
        off: 'SCONTO',
        lightningDeal: 'Offerta Lampo',
        lightningDeals: 'Offerte Lampo',
        lightningDealsHint: 'Si aggiorna ogni ora',
        needohsTitle: 'Negozio NeeDoh Squishy',
        needohsSubtitle: 'Schiaccia ora, aspetta dopo. Ogni NeeDoh viene spedito in 6-9 settimane.',
        needohsShipping: 'Spedizione in 6-9 settimane',
        couponTitle: 'Hai un coupon?',
        couponPlaceholder: 'Inserisci il codice',
        couponApply: 'Applica',
        couponRemove: 'Rimuovi',
        couponSurprise: '🎲 Sorprendimi',
        couponApplied: 'Coupon applicato',
        couponInvalid: 'Codice inesistente. Prova Sorprendimi!',
        couponDiscount: 'Sconto coupon',
        playAndWin: 'Gioca e',
        winFree: 'Vinci Gratis',
        gamesTitle: 'Gioca e vinci premi gratis',
        gamesSubtitle: 'Gira, tira e punta per vincere premi che finiscono nel carrello a 0 €.',
        gamesPrizePool: 'Montepremi',
        gameFree: 'GRATIS',
        gameWheelTitle: 'Gira la Ruota',
        gameWheelDesc: 'Un giro, un premio. Dove si ferma nessuno lo sa.',
        gameSlotTitle: 'Slot Machine',
        gameSlotDesc: 'Allinea tre simboli per vincere il premio corrispondente.',
        gameRouletteTitle: 'Roulette',
        gameRouletteDesc: 'Scegli un colore e gira. Il verde paga il jackpot!',
        gameSpin: 'Gira',
        gamePull: 'Tira la leva',
        gameSpinning: 'Gira...',
        gameYouWon: 'Hai vinto',
        gameTryAgain: 'Per un pelo! Riprova.',
        gameAddFree: 'Aggiungi al carrello gratis',
        gameAddedFree: 'Aggiunto gratis!',
        gameBetLabel: 'Scegli la tua puntata',
        gameBet_red: 'Rosso',
        gameBet_black: 'Nero',
        gameBet_green: 'Verde',
        aboutTitle: 'Perché esiste NeverDeliver',
        aboutLead: 'NeverDeliver è un simulatore di shopping giocoso, in pratica un gioco. Qui niente è reale: nessun prodotto viene spedito, nessuna carta viene addebitata e nessun denaro cambia mai di mano.',
        aboutCareIntro: 'È pensato come un luogo sicuro per godersi il piacere dello shopping senza alcun rischio:',
        aboutCare1: 'Prova la dopamina di cercare offerte, riempire il carrello e “pagare” senza alcuna conseguenza economica.',
        aboutCare2: 'Uno sfogo più delicato per chi soffre di shopping compulsivo o dipendenza dallo shopping.',
        aboutCare3: 'Uno spazio più sicuro per le persone vulnerabili, comprese quelle che convivono con la demenza, che possono essere prese di mira da truffe e negozi online falsi.',
        aboutCare4: 'Un modo a rischio zero per chi ha l’ADHD di soddisfare la voglia di acquisti d’impulso, cercare un po’ di novità e godersi il brivido di un nuovo acquisto senza sensi di colpa.',
        aboutFree: 'Questo progetto è completamente gratuito, senza pubblicità e senza nulla da comprare, e lo sarà sempre.',
        writeReview: 'Scrivi una recensione',
        yourName: 'Il tuo nome',
        reviewTitle: 'Titolo della recensione',
        reviewBody: 'La tua recensione',
        yourRating: 'La tua valutazione',
        submitReview: 'Invia recensione',
        cancel: 'Annulla',
        yourReviewBadge: 'La tua recensione',
        reviewPosted: 'Recensione inviata! (La vedi solo tu.)',
        deleteReview: 'Elimina la mia recensione',
    },
    de: {
        searchPlaceholder: 'Produkte suchen...',
        searchLabel: 'Produkte suchen',
        searchButton: 'Suchen',
        country: 'Land',
        currency: 'Wahrung',
        language: 'Sprache',
        returns: 'Retouren',
        orders: 'und Bestellungen',
        deliverTo: 'Liefern nach',
        welcome: 'Willkommen bei',
        heroLine: 'Groser Katalog, null Lieferstress.',
        freeDelivery: 'KOSTENLOSE Lieferung fur jede imaginare Bestellung',
        results: 'Ergebnisse',
        result: 'Ergebnis',
        page: 'Seite',
        of: 'von',
        previous: 'Zuruck',
        next: 'Weiter',
        sortBy: 'Sortieren nach',
        perPage: 'Pro Seite',
        relevance: 'Relevanz',
        priceLowHigh: 'Preis: aufsteigend',
        priceHighLow: 'Preis: absteigend',
        ratingHighLow: 'Bewertung: hoch nach niedrig',
        newest: 'Neueste',
        retry: 'Erneut versuchen',
        flashSale: 'Blitzangebot',
        saleHeadline: '50% RABATT auf alles',
        saleSubline: 'Jeder Artikel zum halben Preis, sogar die Hauser.',
        saleEndsIn: 'Endet in',
        saveLabel: 'Du sparst',
        off: 'RABATT',
        lightningDeal: 'Blitzangebot',
        lightningDeals: 'Blitzangebote',
        lightningDealsHint: 'Stündlich neu',
        needohsTitle: 'NeeDoh Squishy-Shop',
        needohsSubtitle: 'Jetzt drücken, später warten. Jeder NeeDoh wird in 6-9 Wochen versandt.',
        needohsShipping: 'Versand in 6-9 Wochen',
        couponTitle: 'Hast du einen Gutschein?',
        couponPlaceholder: 'Code eingeben',
        couponApply: 'Anwenden',
        couponRemove: 'Entfernen',
        couponSurprise: '🎲 Überrasch mich',
        couponApplied: 'Gutschein angewendet',
        couponInvalid: 'Diesen Code gibt es nicht. Probier Überrasch mich!',
        couponDiscount: 'Gutschein-Rabatt',
        playAndWin: 'Spiele &',
        winFree: 'Gewinne Gratis',
        gamesTitle: 'Spiele & gewinne Gratis-Preise',
        gamesSubtitle: 'Drehen, ziehen und setzen: Gewinne landen für 0 € im Warenkorb.',
        gamesPrizePool: 'Gewinnpool',
        gameFree: 'GRATIS',
        gameWheelTitle: 'Glücksrad drehen',
        gameWheelDesc: 'Ein Dreh, ein Preis. Wo es stoppt, weiß niemand.',
        gameSlotTitle: 'Spielautomat',
        gameSlotDesc: 'Drei gleiche Symbole gewinnen den passenden Preis.',
        gameRouletteTitle: 'Roulette',
        gameRouletteDesc: 'Wähle eine Farbe und dreh. Grün zahlt den Jackpot!',
        gameSpin: 'Drehen',
        gamePull: 'Hebel ziehen',
        gameSpinning: 'Dreht...',
        gameYouWon: 'Du hast gewonnen',
        gameTryAgain: 'So knapp! Versuch es nochmal.',
        gameAddFree: 'Gratis in den Warenkorb',
        gameAddedFree: 'Gratis hinzugefügt!',
        gameBetLabel: 'Wähle deinen Einsatz',
        gameBet_red: 'Rot',
        gameBet_black: 'Schwarz',
        gameBet_green: 'Grün',
        aboutTitle: 'Warum es NeverDeliver gibt',
        aboutLead: 'NeverDeliver ist ein spielerischer Shopping-Simulator, also ein Spiel. Nichts hier ist echt: Es wird nichts verschickt, keine Karte belastet und es fließt niemals Geld.',
        aboutCareIntro: 'Es ist als sicherer Ort gedacht, um den Spaß am Shopping ganz ohne Risiko zu genießen:',
        aboutCare1: 'Erlebe das Dopamin der Schnäppchenjagd, des Warenkorb-Füllens und des „Bezahlens“, ganz ohne finanzielle Folgen.',
        aboutCare2: 'Ein sanfteres Ventil für alle, die mit zwanghaftem Einkaufen oder Kaufsucht kämpfen.',
        aboutCare3: 'Ein sicherer Raum für gefährdete Menschen, auch für Menschen mit Demenz, die Ziel von Betrug und Fake-Onlineshops werden können.',
        aboutCare4: 'Eine risikofreie Möglichkeit für Menschen mit ADHS, den Drang nach Impulskäufen zu stillen, ein wenig Abwechslung zu suchen und den Reiz eines neuen Kaufs ohne Reue zu genießen.',
        aboutFree: 'Dieses Projekt ist völlig kostenlos, ohne Werbung und ohne etwas zu kaufen, und das bleibt auch so.',
        writeReview: 'Bewertung schreiben',
        yourName: 'Dein Name',
        reviewTitle: 'Titel der Bewertung',
        reviewBody: 'Deine Bewertung',
        yourRating: 'Deine Bewertung',
        submitReview: 'Bewertung absenden',
        cancel: 'Abbrechen',
        yourReviewBadge: 'Deine Bewertung',
        reviewPosted: 'Bewertung gesendet! (Nur du siehst sie.)',
        deleteReview: 'Meine Bewertung löschen',
    },
};

const LanguageContext = createContext(null);

function getInitialLanguage() {
    try {
        const stored = localStorage.getItem(STORAGE_KEY);
        if (LANGUAGES.some(l => l.code === stored)) return stored;
    } catch {
        // ignore
    }
    return 'en';
}

export function LanguageProvider({ children }) {
    const [language, setLanguage] = useState(getInitialLanguage);

    useEffect(() => {
        localStorage.setItem(STORAGE_KEY, language);
    }, [language]);

    const value = useMemo(() => {
        const dictionary = DICT[language] || DICT.en;
        return {
            language,
            languages: LANGUAGES,
            setLanguage(next) {
                if (!LANGUAGES.some(l => l.code === next)) return;
                setLanguage(next);
            },
            t(key) {
                return dictionary[key] || DICT.en[key] || key;
            },
        };
    }, [language]);

    return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error('useLanguage must be used within LanguageProvider');
    return context;
}
